baseURL = 'https://bemaru.github.io/'
languageCode = 'ko'
title = '/bemaru/dev/log'
theme = 'PaperMod'
[pagination]
  pagerSize = 10

[params]
  env = "production"
  description = "Backend Engineer interested in AI Engineering & AI Orchestration."
  author = "bemaru"
  defaultTheme = "dark"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = true

  [params.homeInfoParams]
    Title = "Hi there ðŸ‘‹"
    Content = "Backend Engineer interested in AI Engineering & AI Orchestration."

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/bemaru"

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/jihoon-kwak-94bb08334/"

  [[params.socialIcons]]
    name = "rss"
    url = "/index.xml"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 20

  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 30

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    style = "dracula"
    lineNos = false
